# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f35fb6f7c4719fbd235682e965287f0d4d2551cc343dd35995e1606acdd4fe9a63f11e04a787bcebf032d916653e9629fc18ebea6c8e7206a12f6b5be311f7a

test:
  secret_key_base: c9b1812ed9164f7fc36d7e33f50913f945c83e7b63bf3ad5a45ab212fd8cf6df47bf6365e99a46e01540094a1b8b4f444efd6564f5050f382d2f0e7249debc62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
